# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron:  '7 8 1 * *'


jobs:
  openj9:
    strategy:
      fail-fast: false
      matrix:
        dist: ['temurin', 'semeru']
        version: ['']
        include:
          - dist: 'semeru'
            version: '-ea'

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: ${{ matrix.dist }}
          java-version: 17${{ matrix.release }}
      - run: java -version
      - run: ./gradlew jar
      - run: java -jar build/libs/*.jar
