# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron:  '7 8 1 * *'


jobs:
  openj9:
    strategy:
      fail-fast: false
      matrix:
        impl: ['openj9', 'hotspot']
        release: ['ga']
        include:
          - impl: 'openj9'
            release: 'ea'

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: joschi/setup-jdk@v2
        with:
          java-version: '8'
          architecture: 'x64'
          openjdk_impl: ${{ matrix.impl }}
          release_type: ${{ matrix.release }}
      - run: java -version
      - run: ./gradlew jar
      - run: java -jar build/libs/*.jar
